# Generated by Django 4.1.3 on 2022-12-02 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_transaction_account_active_account_balance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalentry',
            old_name='credit',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='journalentry',
            old_name='credit_currency',
            new_name='amount_currency',
        ),
        migrations.RemoveField(
            model_name='account',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='account',
            name='balance_currency',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='debit',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='debit_currency',
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_JE', to='accounting.account'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='type',
            field=models.CharField(choices=[('SE', 'Simple Entry'), ('CE', 'Compound Entry'), ('OE', 'Opening Entry'), ('TE', 'Transfer Entry'), ('CLE', 'Closing Entry'), ('AE', 'Adjustment Entry'), ('RE', 'Rectifying Entry')], default='SE', max_length=255, verbose_name='Type'),
        ),
    ]
